"""Create matches table

Revision ID: 012bb7e6d548
Revises: 3ae6add4dac8
Create Date: 2025-10-29 00:29:13.344035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012bb7e6d548'
down_revision: Union[str, None] = '3ae6add4dac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotionalprofiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joy', sa.Float(), nullable=False),
    sa.Column('sadness', sa.Float(), nullable=False),
    sa.Column('anxiety', sa.Float(), nullable=False),
    sa.Column('calm', sa.Float(), nullable=False),
    sa.Column('anger', sa.Float(), nullable=False),
    sa.Column('excitement', sa.Float(), nullable=False),
    sa.Column('empathy', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_texts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('matchs',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user1_id', sa.UUID(), nullable=False),
    sa.Column('user2_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('suggested_starters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'passed', 'expired', name='match_status_enum'), nullable=False),
    sa.Column('user1_action', sa.Enum('none', 'connected', 'passed', name='user_action_enum'), nullable=False),
    sa.Column('user2_action', sa.Enum('none', 'connected', 'passed', name='user_action_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('connected_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matchs_compatibility_score'), 'matchs', ['compatibility_score'], unique=False)
    op.create_index(op.f('ix_matchs_status'), 'matchs', ['status'], unique=False)
    op.create_index(op.f('ix_matchs_user1_id'), 'matchs', ['user1_id'], unique=False)
    op.create_index(op.f('ix_matchs_user2_id'), 'matchs', ['user2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchs_user2_id'), table_name='matchs')
    op.drop_index(op.f('ix_matchs_user1_id'), table_name='matchs')
    op.drop_index(op.f('ix_matchs_status'), table_name='matchs')
    op.drop_index(op.f('ix_matchs_compatibility_score'), table_name='matchs')
    op.drop_table('matchs')
    op.drop_table('emotionalprofiles')
    # ### end Alembic commands ###
