"""Create conversations and messages tables

Revision ID: 612e957c4b95
Revises: 012bb7e6d548
Create Date: 2025-10-29 01:16:52.963784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612e957c4b95'
down_revision: Union[str, None] = '012bb7e6d548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
