"""Create user_blocks and reports tables

Revision ID: 6138927e287f
Revises: 612e957c4b95
Create Date: 2025-10-29 10:12:56.361533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6138927e287f'
down_revision: Union[str, None] = '612e957c4b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('profile', 'message', 'photo', 'harassment', 'scam', 'inappropriate_content', 'other', name='report_type_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('content_reference_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'resolved', 'dismissed', name='report_status_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('userblocks',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='_blocker_blocked_uc')
    )
    op.create_index(op.f('ix_userblocks_blocked_id'), 'userblocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_userblocks_blocker_id'), 'userblocks', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userblocks_blocker_id'), table_name='userblocks')
    op.drop_index(op.f('ix_userblocks_blocked_id'), table_name='userblocks')
    op.drop_table('userblocks')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
